export interface RegionData {
  counties: string[];
  subCounties: Record<string, string[]>;
  logisticsProviders: Record<string, string[]>;
  recommendations: Record<string, string[]>;
}

export const KENYA_REGIONS: RegionData = {
  counties: [
    "Mombasa", "Kwale", "Kilifi", "Tana River", "Lamu", "Taita-Taveta", "Garissa", "Wajir", "Mandera", "Marsabit",
    "Isiolo", "Meru", "Tharaka-Nithi", "Embu", "Kitui", "Machakos", "Makueni", "Nyandarua", "Nyeri", "Kirinyaga",
    "Murang'a", "Kiambu", "Turkana", "West Pokot", "Samburu", "Trans Nzoia", "Uasin Gishu", "Elgeyo-Marakwet", "Nandi", "Baringo",
    "Laikipia", "Nakuru", "Narok", "Kajiado", "Kericho", "Bomet", "Kakamega", "Vihiga", "Bungoma", "Busia",
    "Siaya", "Kisumu", "Homa Bay", "Migori", "Kisii", "Nyamira", "Nairobi"
  ],
 subCounties: {
  "Mombasa": ["Changamwe", "Jomvu", "Kisauni", "Likoni", "Mvita", "Nyali"],
  "Kwale": ["Kinango", "Lunga Lunga", "Matuga", "Msambweni"],
  "Kilifi": ["Ganze", "Kaloleni", "Kilifi North", "Kilifi South", "Magarini", "Malindi", "Rabai"],
  "Tana River": ["Bura", "Galole", "Garsen"],
  "Lamu": ["Lamu East", "Lamu West"],
  "Taita Taveta": ["Mwatate", "Taveta", "Voi", "Wundanyi"],
  "Garissa": ["Balambala", "Dadaab", "Fafi", "Garissa Township", "Ijara", "Lagdera"],
  "Wajir": ["Eldas", "Tarbaj", "Wajir East", "Wajir North", "Wajir South", "Wajir West"],
  "Mandera": ["Banissa", "Lafey", "Mandera East", "Mandera North", "Mandera South", "Mandera West"],
  "Marsabit": ["Laisamis", "Moyale", "North Horr", "Saku"],
  "Isiolo": ["Isiolo", "Merti", "Garbatulla"],
  "Meru": ["Buuri", "Igembe Central", "Igembe North", "Igembe South", "North Imenti", "South Imenti", "Tigania East", "Tigania West"],
  "Tharaka Nithi": ["Chuka", "Igambang'ombe", "Maara", "Muthambi"],
  "Embu": ["Manyatta", "Mbeere North", "Mbeere South", "Runyenjes"],
  "Kitui": ["Kitui Central", "Kitui East", "Kitui Rural", "Kitui South", "Kitui West", "Mwingi Central", "Mwingi North", "Mwingi West"],
  "Machakos": ["Athi River", "Kangundo", "Kathiani", "Machakos Town", "Masinga", "Matungulu", "Mavoko", "Mwala", "Yatta"],
  "Makueni": ["Kaiti", "Kibwezi East", "Kibwezi West", "Kilome", "Makueni", "Mbooni"],
  "Nyandarua": ["Kinangop", "Kipipiri", "Ndaragwa", "Ol Kalou", "Ol Jorok"],
  "Nyeri": ["Kieni East", "Kieni West", "Mathira East", "Mathira West", "Mukurweini", "Nyeri Central", "Othaya", "Tetu"],
  "Kirinyaga": ["Gichugu", "Kirinyaga Central", "Kirinyaga East", "Mwea East", "Mwea West"],
  "Murang'a": ["Gatanga", "Kahuro", "Kandara", "Kangema", "Kigumo", "Kiharu", "Maragwa", "Mathioya"],
  "Kiambu": ["Gatundu North", "Gatundu South", "Githunguri", "Juja", "Kabete", "Kiambaa", "Kiambu Town", "Kikuyu", "Limuru", "Ruiru", "Thika Town", "Lari"],
  "Turkana": ["Kibish", "Loima", "Turkana Central", "Turkana East", "Turkana North", "Turkana South", "Turkana West"],
  "West Pokot": ["Kacheliba", "Kapenguria", "Pokot South"],
  "Samburu": ["Samburu Central", "Samburu East", "Samburu North"],
  "Trans Nzoia": ["Cherangany", "Endebess", "Kiminini", "Kwanza", "Saboti"],
  "Uasin Gishu": ["Ainabkoi", "Kapseret", "Kesses", "Moiben", "Soy", "Turbo"],
  "Elgeyo Marakwet": ["Keiyo North", "Keiyo South", "Marakwet East", "Marakwet West"],
  "Nandi": ["Aldai", "Chesumei", "Emgwen", "Mosop", "Nandi Central", "Nandi East", "Tinderet"],
  "Baringo": ["Baringo Central", "Baringo North", "Baringo South", "Eldama Ravine", "Mogotio", "Tiaty"],
  "Laikipia": ["Laikipia East", "Laikipia North", "Laikipia West"],
  "Nakuru": ["Bahati", "Gilgil", "Kuresoi North", "Kuresoi South", "Molo", "Naivasha", "Nakuru East", "Nakuru West", "Njoro", "Rongai", "Subukia"],
  "Narok": ["Emurua Dikirr", "Kilgoris", "Narok East", "Narok North", "Narok South", "Narok West"],
  "Kajiado": ["Isinya", "Kajiado Central", "Kajiado East", "Kajiado North", "Kajiado West", "Loitokitok"],
  "Kericho": ["Ainamoi", "Belgut", "Bureti", "Kipkelion East", "Kipkelion West", "Soin/Sigowet"],
  "Bomet": ["Bomet Central", "Bomet East", "Chepalungu", "Konoin", "Sotik"],
  "Kakamega": ["Butere", "Ikolomani", "Khwisero", "Likuyani", "Lugari", "Lurambi", "Malava", "Matungu", "Mumias East", "Mumias West", "Navakholo", "Shinyalu"],
  "Vihiga": ["Emuhaya", "Hamisi", "Luanda", "Sabatia", "Vihiga"],
  "Bungoma": ["Bumula", "Kabuchai", "Kanduyi", "Kimilili", "Mt Elgon", "Sirisia", "Tongaren", "Webuye East", "Webuye West"],
  "Busia": ["Budalangi", "Butula", "Funyula", "Matayos", "Nambale", "Samia", "Teso North", "Teso South"],
  "Siaya": ["Alego Usonga", "Bondo", "Gem", "Rarieda", "Ugenya", "Ugunja"],
  "Kisumu": ["Kisumu Central", "Kisumu East", "Kisumu West", "Muhoroni", "Nyakach", "Nyando", "Seme"],
  "Homa Bay": ["Homa Bay Town", "Kabondo Kasipul", "Karachuonyo", "Kasipul", "Mbita", "Ndhiwa", "Rangwe", "Suba"],
  "Migori": ["Awendo", "Kuria East", "Kuria West", "Nyatike", "Rongo", "Suna East", "Suna West", "Uriri"],
  "Kisii": ["Bonchari", "Bobasi", "Bomachoge Borabu", "Bomachoge Chache", "Kitutu Chache North", "Kitutu Chache South", "Nyaribari Chache", "Nyaribari Masaba", "South Mugirango"],
  "Nyamira": ["Borabu", "Manga", "Masaba North", "Nyamira North", "Nyamira South"],
  "Nairobi": ["Dagoretti North", "Dagoretti South", "Embakasi Central", "Embakasi East", "Embakasi North", "Embakasi South", "Embakasi West", "Kamukunji", "Kasarani", "Kibra", "Lang'ata", "Makadara", "Mathare", "Roysambu", "Ruaraka", "Starehe", "Westlands"]
},
  logisticsProviders: {
    "Mombasa": ["Coastline Logistics", "Port City Movers"],
    "Kwale": ["South Coast Transporters"],
    "Kilifi": ["Kilifi Cargo Services"],
    "Tana River": ["Tana Delta Transport"],
    "Lamu": ["Lamulink Logistics"],
    "Taita-Taveta": ["Voi Link Transporters"],
    "Garissa": ["Garissa Express"],
    "Wajir": ["Wajir Cargo"],
    "Mandera": ["Mandera Transporters"],
    "Marsabit": ["Marsabit Movers"],
    "Isiolo": ["Isiolo Link"],
    "Meru": ["Meru Farmers Transport", "Mount Kenya Logistics"],
    "Tharaka-Nithi": ["Tharaka Transporters"],
    "Embu": ["Embu Farmers Link"],
    "Kitui": ["Kitui Logistics"],
    "Machakos": ["Machakos Cargo Services"],
    "Makueni": ["Makueni Transporters"],
    "Nyandarua": ["Nyandarua Farm Movers"],
    "Nyeri": ["Nyeri Agro-Trans"],
    "Kirinyaga": ["Kirinyaga Logistics"],
    "Murang'a": ["Murang'a Transporters"],
    "Kiambu": ["Kiambu Farm Movers"],
    "Turkana": ["Turkana Cargo"],
    "West Pokot": ["West Pokot Transporters"],
    "Samburu": ["Samburu Link"],
    "Trans Nzoia": ["Trans Nzoia Movers"],
    "Uasin Gishu": ["North Rift Logistics", "Eldoret Farm Movers"],
    "Elgeyo-Marakwet": ["Elgeyo Transporters"],
    "Nandi": ["Nandi Movers"],
    "Baringo": ["Baringo Transporters"],
    "Laikipia": ["Laikipia Cargo"],
    "Nakuru": ["Nakuru Agro-Trans", "Rift Valley Carriers"],
    "Narok": ["Narok Movers"],
    "Kajiado": ["Kajiado Transporters"],
    "Kericho": ["Kericho Cargo"],
    "Bomet": ["Bomet Transporters"],
    "Kakamega": ["Kakamega Logistics"],
    "Vihiga": ["Vihiga Movers"],
    "Bungoma": ["Bungoma Cargo"],
    "Busia": ["Busia Transporters"],
    "Siaya": ["Siaya Logistics"],
    "Kisumu": ["Lake Basin Transporters", "Kisumu Cargo Services"],
    "Homa Bay": ["Homa Bay Movers"],
    "Migori": ["Migori Transporters"],
    "Kisii": ["Kisii Logistics"],
    "Nyamira": ["Nyamira Movers"],
    "Nairobi": ["Nairobi Express Logistics", "City Transporters", "FastTrack Couriers"]
  },
  recommendations: {
    "Mombasa": ["Focus on coconut and cashewnut production.", "Excellent for exotic fruit farming."],
    "Kwale": ["Ideal for mango and cashew farming."],
    "Kilifi": ["Suitable for cassava and coconut farming."],
    "Tana River": ["Good for mango and green gram production."],
    "Lamu": ["Focus on coconut and sesame production."],
    "Taita-Taveta": ["Good for horticultural crops like tomatoes and onions."],
    "Garissa": ["Focus on livestock farming and melons."],
    "Wajir": ["Suitable for camel farming and livestock management."],
    "Mandera": ["General livestock and onion production."],
    "Marsabit": ["Livestock focus, specifically cattle and camels."],
    "Isiolo": ["Adaptable for livestock and some irrigation"],
    "Meru": ["World-class region for Miraa and Coffee."],
    "Tharaka-Nithi": ["Good for maize and millet."],
    "Embu": ["Focus on coffee and tea production."],
    "Kitui": ["Drought-resistant crops like green grams are ideal."],
    "Machakos": ["Well-known for mango and vegetable production."],
    "Makueni": ["Good for mangoes and pulses."],
    "Nyandarua": ["Excellent for potatoes and cabbages."],
    "Nyeri": ["Prime area for coffee and tea."],
    "Kirinyaga": ["Focus on rice and horticultural crops."],
    "Murang'a": ["Excellent for tea and coffee."],
    "Kiambu": ["Coffee and high-value horticulture."],
    "Turkana": ["Irrigation schemes for sorghum."],
    "West Pokot": ["Livestock and maize farming."],
    "Samburu": ["Primary focus on livestock."],
    "Trans Nzoia": ["Large-scale maize production."],
    "Uasin Gishu": ["Prime region for large-scale maize and wheat."],
    "Elgeyo-Marakwet": ["Good for potato and pyrethrum."],
    "Nandi": ["Tea production is primary."],
    "Baringo": ["Sorghum and livestock management."],
    "Laikipia": ["Maize and horticultural crops."],
    "Nakuru": ["Excellent for potato and pyrethrum farming."],
    "Narok": ["Known for wheat and maize."],
    "Kajiado": ["Livestock and horticultural farming."],
    "Kericho": ["Tea farming is dominant."],
    "Bomet": ["Tea and dairy farming."],
    "Kakamega": ["General maize and dairy farming."],
    "Vihiga": ["Small-scale maize and vegetable farming."],
    "Bungoma": ["Large-scale maize and sugarcane."],
    "Busia": ["Focus on maize and cassava."],
    "Siaya": ["Maize, beans, and fish farming."],
    "Kisumu": ["Ideal for rice farming in irrigation schemes."],
    "Homa Bay": ["Maize, beans, and fish farming."],
    "Migori": ["Sugar cane and tobacco."],
    "Kisii": ["Bananas and horticultural produce."],
    "Nyamira": ["Tea and horticultural farming."],
    "Nairobi": ["Focus on vertical farming due to limited space."]
  }
};
